const products = [
  {
    id: "p1",
    title: "Bamboo Fiber Dinnerware Set",
    image: "https://i.imgur.com/l9IGZpP.png",
    discount: "25% OFF",
    badge: "A+",
    rating: 4,
    reviews: 124,
    plastic: 91,
    chemical: 31,
    certificates: [
      { name: "100% Organic", icon: "🌿" },
      { name: "Recyclable", icon: "♻️" },
    ],
    price: 29.99,
    originalPrice: 39.99,
  },
  {
    id: "p2",
    title: "Organic Cotton Reusable Produce Bags",
    image: "https://i.imgur.com/FBLw1zN.png",
    discount: "",
    badge: "A",
    rating: 4,
    reviews: 70,
    plastic: 71,
    chemical: 19,
    certificates: [
      { name: "100% Organic", icon: "🌿" },
      { name: "GreenCircle Certified", icon: "🔵" },
    ],
    price: 14.99,
  },
  {
    id: "p3",
    title: "Solar-Powered Garden Lights",
    image: "https://i.imgur.com/1VznX0E.png",
    discount: "BESTSELLER",
    badge: "A+",
    rating: 4,
    reviews: 67,
    plastic: 84,
    chemical: 19,
    certificates: [
      { name: "Green Business Certified", icon: "📄" },
      { name: "Recyclable", icon: "♻️" },
    ],
    price: 34.99,
    originalPrice: 44.99,
  },
  {
    id: "p4",
    title: "Natural Loofah Body Scrubbers",
    image: "https://i.imgur.com/rbF3gfD.png",
    discount: "",
    badge: "A",
    rating: 4,
    reviews: 156,
    plastic: 84,
    chemical: 19,
    certificates: [
      { name: "100% Organic", icon: "🌿" },
      { name: "Recyclable", icon: "♻️" },
    ],
    price: 12.99,
  },
  {
    id: "p5",
    title: "Reusable Stainless Steel Straws",
    image: "https://i.imgur.com/mTD9Rph.png",
    discount: "10% OFF",
    badge: "A+",
    rating: 5,
    reviews: 210,
    plastic: 98,
    chemical: 5,
    certificates: [
      { name: "BPA Free", icon: "🚫" },
      { name: "Recyclable", icon: "♻️" },
    ],
    price: 9.99,
    originalPrice: 10.99,
  },
  {
    id: "p6",
    title: "Eco-Friendly Bamboo Toothbrush Set",
    image: "https://i.imgur.com/Hv3KDfD.png",
    discount: "",
    badge: "A",
    rating: 4,
    reviews: 98,
    plastic: 95,
    chemical: 10,
    certificates: [
      { name: "100% Organic", icon: "🌿" },
      { name: "Compostable", icon: "🌱" },
    ],
    price: 7.99,
  },
  {
    id: "p7",
    title: "Recycled Paper Notebooks",
    image: "https://i.imgur.com/4eFWBzH.png",
    discount: "15% OFF",
    badge: "A+",
    rating: 5,
    reviews: 55,
    plastic: 100,
    chemical: 0,
    certificates: [
      { name: "FSC Certified", icon: "📄" },
      { name: "Recyclable", icon: "♻️" },
    ],
    price: 5.49,
    originalPrice: 6.49,
  },
  {
    id: "p8",
    title: "Plant-Based Laundry Detergent",
    image: "https://i.imgur.com/s7kBqX7.png",
    discount: "",
    badge: "A",
    rating: 4,
    reviews: 134,
    plastic: 85,
    chemical: 12,
    certificates: [
      { name: "EcoLabel Certified", icon: "🧼" },
      { name: "Biodegradable", icon: "🌎" },
    ],
    price: 19.99,
  },
];

export default products;
